---
lang: pt-BR
title: "Cronograma"
---

Nesta página, você encontrará o cronograma completo da disciplina, com
links para os materiais de cada aula, incluindo slides, links para 
tutoriais criados para a disciplina, arquivos quarto (.qmd), 
artigos, e outros recursos que poderão ser disponibilizados.


# Semana 1

## Aula 1 (27/03/2025) 

- **Tópicos:**
  
   - Apresentação da disciplina
  - O que é Ciência de Dados?

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n" para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::  
  
  <iframe src="/slides/slides_aula01.html" width="100%" height="450px"></iframe>
  
  - [slides: versão para download (.zip)](arquivos/slides_aula01.zip)


- **Artigos citados**
  
  - [The History of Data Economy I, II, III, IV - pdf](/arquivos/history_of_data_economy.pdf){target="_blank"} 
  
  
- **Tutoriais**
  
  - [Introdução ao RStudio](https://washingtonsilva.github.io/tutorials/rstudio/){target="_blank"}
  
  - [Introdução ao Sistema Quarto](https://washingtonsilva.github.io/tutorials/quarto/){target="_blank"}
  
  - [Markdown](https://washingtonsilva.github.io/tutorials/markdown/){target="_blank"}
  
  - [Introdução à Linguagem R](https://washingtonsilva.github.io/tutorials/R/){target="_blank"}
  
  - [Controle de Versão com Git e GitHub](https://washingtonsilva.github.io/tutorials/git/){target="_blank"}




# Semana 2

## Aula 2 (03/04/2025) 

- **Tópicos:**

  - Metodologia CRISP-DM
  - Tipos de Análise de Dados
  - Introdução ao RStudio 
  - Introdução ao Sistema de Publicação Quarto
  - Introdução ao Git e GitHub
  - Fluxo de trabalho integrando RStudio/Quarto/R/Git/GitHub

  
- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n"   para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::
  
  <iframe src="/slides/slides_aula02.html" width="100%" height="450px"></iframe>
  
  - [slides: versão para download (.zip)](arquivos/slides_aula02.zip)
  

- **CRISP-DM**

  - [Guia CRISP-DM da IBM](arquivos/guia-ibm-crispdm.pdf){target="_blank"}


- **Arquivo de dados**

  - [productionlog_sample (.csv)](arquivos/productionlog_sample.csv)


- **Arquivo quarto**

  - [01-relatorio-html (.zip)](arquivos/01-relatorio-html.zip)


::: {.callout-tip}
## Como verificar e configurar seu perfil do Git em um computador?

**Configurando seu perfil no Git**

Após instalar o Git em um computador, digite os comandos abaixo 
no Git Bash (Windows) ou em um terminal (Linux/macOS), substituindo 
"Seu Nome" pelo nome de usuario que deseja usar (ex: maria_silva) 
e "seu.email@exemplo.com" pelo seu email para configurar um nome de 
usuário e email globalmente:

```{.bash}
git config --global user.name "Seu Nome"
git config --global user.email "seu.email@exemplo.com"
```

É importante usar o mesmo nome e email em todos os computadores para 
manter a consistência na atribuição dos seus commits.

**Verificando sua configuração do Git**

Para verificar suas configurações atuais:

```{.bash}
# Para verificar o nome configurado
git config --global user.name

# Para verificar o email configurado
git config --global user.email

# Para listar todas as configurações do Git
git config --list
```

**Observação:** Se omitir a flag `--global`, você verá apenas as 
configurações específicas do repositório atual, se existirem.
::::  




# Semana 3

## Aula 3 (10/04/2025) 

- **Tópicos:**

  - Breve revisão sobre o RStudio 
  - Sistema de publicação Quarto: (continuação)
  - Introdução ao Git e GitHub:  (continuação)
  - Sessão prática: Fluxo de trabalho integrando RStudio/Quarto/R/Git/GitHub

  
- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n"   para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::
  
  <iframe src="/slides/slides_aula03.html" width="100%" height="450px"></iframe>
  
  - [slides: versão para download (.zip)](arquivos/slides_aula03.zip)


- **Arquivo compactado**

  - [aula03.zip](arquivos/aula03.zip)
  



# Semana 4

## Aula 4 (24/04/2025) 

- **Tópicos:**

  - Conceitos de Variáveis e Observações em Estatística
  - Conceito de Dados Organizados (*Tidy Data*)
  - Tipos atômicos e classes principais de dados da linguagem R
  - Abordar os Tipos de Dados Tradicionais em Finanças
  - Importação e Preparação de Dados Típicos de Finanças com 
    exemplos práticos.

  
- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n"   para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::
  
  <iframe src="/slides/slides_aula04.html" width="100%" height="450px"></iframe>
  
  - [slides: versão para download (.zip)](arquivos/slides_aula04.zip)


- **Arquivos compactados para a aula**

  - [data_aula04.zip](arquivos/data_aula04.zip)
  - [04-report.zip](arquivos/04-report.zip)




# Semana 5

## Aula 5 (08/05/2025) 

- **Tópicos:**

  - Metodologia CRISP-DM: Fases 2 e 3 
  - Revisão sobre Dados Organizados (*Tidy Data*) 
  - Introdução ao Pacote tidyr: função pivot_longer() 
  - Introdução ao Pacote dplyr: funções select() e filter() 

  
- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n"   para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::
  
  <iframe src="/slides/slides_aula05.html" width="100%" height="450px"></iframe>
  
  - [slides: versão para download (.zip)](arquivos/slides_aula05.zip)


- **Arquivo quarto para a aula**

  - [05-report.zip](arquivos/05-report.zip)




# Semana 6

## Aula 6 (15/05/2025) 

- **Tópicos:**

  - Introdução ao Pacote dplyr:

    - Função mutate
    - Funções group_by e summarize

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n"   para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::
  
  <iframe src="/slides/slides_aula06.html" width="100%" height="450px"></iframe>
  
  - [slides: versão para download (.zip)](arquivos/slides_aula06.zip)

- **Artigo para Leitura**
  
  - [How to Pick a Programming Language - Nature 640, 1116-1117 (2025)](/arquivos/d41586-025-01241-6.pdf){target="_blank"}




# Semana 7

## Aula 7 (22/05/2025) 

- **Tópicos:**

  - Pacote dplyr: Tipos Básicos de *joins*

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n"   para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::
  
  <iframe src="/slides/slides_aula07.html" width="100%" height="450px"></iframe>
  
  - [slides: versão para download (.zip)](arquivos/slides_aula07.zip)


- **Arquivo quarto para a aula**

  - [06-report.zip](arquivos/06-report.zip)




# Semana 8

## Aula 8 (29/05/2025)

- **Tópico:**

  - Avaliação 1

::: {.callout-tip}
## Avaliação 1 

[**Clique aqui para acessar a Avaliação 1**](/arquivos/01-avaliacao.html){target="_blank"}

[**Clique aqui para informações sobre os dados das Questões 4 e 5**](/arquivos/info_dados_exercicios.html){target="_blank"}
:::


- **Arquivos necessários**

  - [dados_franco2022.zip](arquivos/dados_franco2022.zip) - arquivo de dados
  - [01-avaliacao-template.zip](arquivos/01-avaliacao-template.zip) - template de arquivo quarto para resolução da avaliação 



::: {.callout-tip}
## Estruturando seu Projeto RStudio para a Avaliação 1

1. Abra o RStudio e o seu Projeto RStudio da disciplina.

2. Baixe o arquivo de dados **dados_franco2022.zip**, descompacte esse arquivo, 
copie/recorte o arquivo `dados_franco2022.csv` e salve-o na subpasta 
**raw** da pasta **data** do seu Projeto RStudio

3. Crie uma pasta chamada **avaliacoes** na raiz do seu Projeto RStudio

4. Dentro da pasta **avaliacoes** , crie uma subpasta chamada **01-avaliacao**

5. Baixe o arquivo **01-avaliacao-template.zip**, descompacte esse arquivo, 
copie/recorte o arquivo `01-avaliacao-template.qmd` e salve-o na 
subpasta **01-avaliacao** que você acabou de criar

6. Renomeie o arquivo `01-avaliacao-template.qmd` para 
`01-avaliacao-seunome.qmd`

7. Escreva seu nome na chave `author: "SEU NOME AQUI"` do cabeçalho yaml 
e resolva as questões
:::




::: {.callout-tip}
## Instruções para Envio da Resolução da Avaliação 1

1. Compacte seu arquivo HTML em um arquivo ZIP 
(`01-avaliacao-seunome.zip`)

2. Atualize o repositório no github de seu projeto RStudio da 
disciplina, que deve conter sua resolução da avaliação.

3. Envie o arquivo compactado e o link do seu repositório no 
github para o email **washington.silva@ifmg.edu.br**, 
use o assunto: **Avaliação 1 - MPA**.
:::




# Semana 9

## Aula 9 (05/06/2025) 

- **Tópicos:**

  - Fundamentos de Probabilidade e Simulação - Parte 1

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n"   para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::
  
  <iframe src="/slides/slides_aula08.html" width="100%" height="450px"></iframe>
  
  - [slides: versão para download (.zip)](arquivos/slides_aula08.zip)


- **Arquivo quarto para a aula**

  - [07-report.zip](arquivos/07-report.zip)




# Semana 10

## Aula 10 (12/06/2025) 

- **Tópicos:**

  - Fundamentos de Probabilidade e Simulação - Parte 2

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n"   para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::
  
  <iframe src="/slides/slides_aula09.html" width="100%" height="450px"></iframe>
  
  - [slides: versão para download (.zip)](arquivos/slides_aula09.zip)




# Semana 11

## Aula 11 (26/06/2025) 

- **Tópicos:**

  - Fundamentos de Probabilidade e Simulação - Parte 3

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n"   para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::
  
  <iframe src="/slides/slides_aula10.html" width="100%" height="450px"></iframe>
  
  - [slides: versão para download (.zip)](arquivos/slides_aula10.zip)

- **Arquivo quarto para a aula**

  - [08-report.zip](arquivos/08-report.zip)





# Semana 12

## Aula 12 (03/07/2025) 

- **Tópicos:**

  - Fundamentos de Estatística - Parte 1

- **Slides:**

  ::: {.callout-tip}
  ## Para navegar e visualizar 
  
  Clique no símbolo > à direita ou use as teclas: seta para direita →, espaço, 
  ou letra "n"   para avançar. Pressione "F" para modo de tela cheia e "Esc" 
  para sair.
  :::
  
  <iframe src="/slides/slides_aula11.html" width="100%" height="450px"></iframe>
  
  - [slides: versão para download (.zip)](arquivos/slides_aula11.zip)

- **Arquivo quarto para a aula**

  - [09-report.zip](arquivos/09-report.zip)


