---
lang: pt-BR
title: "Introdução à Ciência de Dados 2025"
subtitle: "Mestrado Profissional em Administração <br> IFMG Campus Formiga"
---

## Bem-vindo à disciplina

Esta disciplina objetiva equipar os mestrandos com conhecimentos fundacionais e 
ferramentas modernas para conduzirem projetos de pesquisa empírica 
reproduzíveis na área de Finanças, desenvolvendo capacidade crítica para 
implementar modelos empíricos robustos, interpretar resultados e comunicar 
análises computacionais no contexto de Finanças e de áreas correlacionadas.

## Informações Gerais

- **Professor:** [Prof. Dr. Washington Santos da Silva](https://washingtonsilva.github.io){target="_blank"}
- **E-mail:** washington.silva@ifmg.edu.br
- **Horário de aula:** Quinta-Feira, 18:30-20:30
- **Local:** Laboratório de Informática **2** - Bloco B - 2$^{o}$ andar.

## Conteúdo

O conteúdo da disciplina está organizado na página
[Cronograma](cronograma.qmd), onde você encontrará os materiais 
necessários para acompanhar as aulas, incluindo slides, arquivos Quarto, 
tutoriais, entre outros.

O programa da disciplina está disponível na página 
[Programa da Disciplina](programa.qmd), nela você encontrará informações 
detalhadas sobre objetivos, ementa, bibliografia, avaliações, entre outras.